
/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Jan 7, 2020
*/


/*
DROP TABLE IF EXISTS `articles`;
DROP TABLE IF EXISTS `news_sources`;
*/


CREATE TABLE `news_sources` (
    `id` INT (10) NOT NULL AUTO_INCREMENT,
    `rss` VARCHAR (100),
    `catId` INT (10) DEFAULT 1,
    `fail` INT (10) DEFAULT 0,
    `activ` SET ('0', '1') DEFAULT 1,
    PRIMARY KEY (`id`),
    UNIQUE INDEX news_sources_rss_unique (`rss`)
)

CREATE TABLE `articles` (
    `id` INT (10) NOT NULL AUTO_INCREMENT,
    `guId` VARCHAR (100),
    `sourceId` INT (10),
    `title` VARCHAR (100),
    `description` VARCHAR (100),
    `img` VARCHAR (100),
    `url` VARCHAR (100),
    `articleDate` VARCHAR (100),
    `catId` INT (10) DEFAULT 1,
    PRIMARY KEY (`id`),
    UNIQUE INDEX articles_gu_id_unique (`guId`)
)

ALTER TABLE `articles`
ADD FOREIGN KEY news_sources_articles_fk (`sourceId`) REFERENCES `news_sources`(`id`);




